spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gift_certificates_db?useUnicode=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rtyfghvbn
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true